# Generated by Django 6.1 on 2026-08-15 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_piasters', models.PositiveIntegerField(help_text='Amount in piasters (10000 = 100.00 EGP)')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed')], db_index=True, default='pending', max_length=10)),
                ('paymob_intention_id', models.CharField(blank=True, max_length=100)),
                ('paymob_transaction_id', models.CharField(blank=True, help_text='Paymob obj.id — unique for idempotent webhook handling', max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='jobs.order')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
