# Generated by Django 6.1 on 2026-08-15 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='accounts.customer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_type', models.CharField(choices=[('customer', 'Customer'), ('mechanic', 'Mechanic'), ('system', 'System')], max_length=10)),
                ('body', models.TextField(blank=True)),
                ('audio', models.FileField(blank=True, null=True, upload_to='messages/audio/')),
                ('channel', models.CharField(choices=[('web', 'Web'), ('whatsapp', 'WhatsApp')], default='web', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='jobs.conversation')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending_review', 'Pending review'), ('quoted', 'Quoted'), ('in_progress', 'In progress'), ('ready_for_pickup', 'Ready for pickup'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='pending_review', max_length=20)),
                ('quoted_price', models.DecimalField(blank=True, decimal_places=2, help_text='Snapshotted EGP price at quote time', max_digits=10, null=True)),
                ('kareem_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='accounts.customer')),
                ('diagnostic', models.ForeignKey(blank=True, help_text='Source template used at quote time', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='catalog.diagnostic')),
                ('labels', models.ManyToManyField(blank=True, related_name='orders', to='catalog.label')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='conversation',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='jobs.order'),
        ),
        migrations.CreateModel(
            name='OrderStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('expected_minutes', models.PositiveIntegerField(default=30)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='jobs.order')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
