# Generated by Django 6.1 on 2026-08-15 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_conversation_order_onetoone'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='wa_message_id',
            field=models.CharField(
                blank=True,
                help_text='WhatsApp Cloud API message id; webhook idempotency.',
                max_length=255,
                null=True,
                unique=True,
            ),
        ),
    ]
