# Generated by Django 6.1 on 2026-08-15 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_message_wa_message_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending_review', 'Pending review'), ('quoted', 'Quoted'), ('paid', 'Paid'), ('in_progress', 'In progress'), ('ready_for_pickup', 'Ready for pickup'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='pending_review', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderstep',
            name='description_ar',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='orderstep',
            name='description_en',
            field=models.TextField(blank=True),
        ),
    ]
