# Generated by Django 6.1 on 2026-08-15 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_bilingual_titles'),
        ('jobs', '0006_order_paid_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='suggested_diagnostic',
            field=models.ForeignKey(blank=True, help_text='Tagger suggestion for Kareem to confirm or override at quote time', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggested_orders', to='catalog.diagnostic'),
        ),
    ]
