# Generated by Django 6.1 on 2026-08-15 12:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(help_text='E.164 format, e.g. +201012345678', max_length=16, unique=True, validators=[django.core.validators.RegexValidator(message='Phone must be E.164 format (e.g. +201012345678).', regex='^\\+[1-9]\\d{1,14}$')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
