# Generated by Django 6.1 on 2026-08-15 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_bilingual_titles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosticstep',
            name='description_ar',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='diagnosticstep',
            name='description_en',
            field=models.TextField(blank=True),
        ),
    ]
